version: '3'
services:

  green:
    container_name: green
    image: llimy1/volunteer
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GOOGLE_URL: ${GOOGLE_URL}
      NAVER_ID: ${NAVER_ID}
      NAVER_SECRET: ${NAVER_SECRET}
      NAVER_URL: ${NAVER_URL}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_URL: ${KAKAO_URL}
      JWT_SECRET: ${JWT_SECRET}

  blue:
    container_name: blue
    image: llimy1/volunteer
    ports:
      - "8081:8080"
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GOOGLE_URL: ${GOOGLE_URL}
      NAVER_ID: ${NAVER_ID}
      NAVER_SECRET: ${NAVER_SECRET}
      NAVER_URL: ${NAVER_URL}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_URL: ${KAKAO_URL}
      JWT_SECRET: ${JWT_SECRET}

