spring:
  profiles:
    include:
      - db
      - aws
      - jwt
      - oauth

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
