spring:
  profiles:
    active: prod
    include:
      - db
      - aws
      
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true


