spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: authspringbucket
    credentials:
      access-key: AKIAT45S5LPZUUA7FHWK
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false


# aws 오류 안뜨게 하는 어쩌구입니다.
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error