spring:
  profiles:
    active: prod
    include:
      - db
      - aws
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true


