spring:
  profiles:
    include:
      - db
      - aws
      - jwt
      - oauth
  # ??? swagger ??? ?? ?? ????.
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # ???? update? ?? ????
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true