spring:
   # DB 비밀번호, DB 이름 부분을 본인이 사용하는 것으로 교체 해주면 됩니다.
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8

