cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false


# aws 오류 안뜨게 하는 어쩌구입니다.
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error