spring:
  # DB 비밀번호, DB 이름 부분을 본인이 사용하는 것으로 교체 해주면 됩니다.
  datasource:
    username: root
    password: { DB 비밀번호 }
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/{DB이름}?useUnicode=true&characterEncoding=UTF-8