spring:
  profiles:
    include:
      - db
      - aws
      - jwt
      - oauth
    active: prod

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

